### ISSUE TITLE
Noisy point cloud 

### ISSUE THREAD

**Issue by versatran01** [diode-dataset/diode-devkit#3]
![Selection_010](https://user-images.githubusercontent.com/1883423/66419861-cfc97080-e9d2-11e9-9318-7c2e081fceb4.png)

![Selection_011](https://user-images.githubusercontent.com/1883423/66419927-eff92f80-e9d2-11e9-8abc-6db6bb131079.png)

Hi, thanks for the dataset. However, when visualizing the data as point cloud, points on the intensity edges are very noisy, which suggests that the depth values are wrong at those points? Any idea how to fix this?

**Comment by ivasiljevic** [comment]
Some number of spurious returns on edges is unavoidable (an artifact of the sensor), when visualizing a depth map as a point cloud with large-ish points the noise appears magnified -- for visualization purposes I'd use something like [this](https://github.com/ialhashim/DenseDepth/blob/master/demo.py#L344) from the DenseDepth visualization code, it should give you a clean pointcloud visualization.

**Comment by versatran01** [comment]
Ok, but your fix is only for visualization right? The ground truth is still bad for training.

**Comment by ivasiljevic** [comment]
A physical limitation of sensors like this is that there is going to be some noise around depth discontinuities -- we chose to provide the raw depth map so that (if they like) users can devise their own masking/smoothing strategies.  We also provide automated masks but these are liberal in the depth they allow through (we found it difficult to maintain faraway thin structures while filtering out all the noisy depth edges).

Given that it's only a small fraction of the pixels we didn't find this to be a problem during training.

**Comment by kwea123** [comment]
there is huge edge artifact on indoor scenes: [see here](https://photos.google.com/share/AF1QipPyLaqs5kjmZMQvafBrLfP37Q08Ms5-bmO-Y2d09-HD0UKaxfdBYuqs6UgaFG7oag?pli=1&key=U3ZTN2htZl9SUzhTYW83UWtiNEFaZGVHZGlXSHdn)
It degrades the quality a lot, I recommend not training with these data
